### ISSUE TITLE
TypeError: mediaRecorder.record is not a function

### ISSUE THREAD

**Issue by Perezmarc** [muaz-khan/RecordRTC#109]
Am I the only one getting this error?

```
main.bundle.js:28029 TypeError: mediaRecorder.record is not a function
    at initRecorder (https://webrtcexperiment-webrtc.netdna-ssl.com/RecordRTC.js:80:23)
    at Object.startRecording (https://webrtcexperiment-webrtc.netdna-ssl.com/RecordRTC.js:60:9)
    at RecorderComponent.successCallback (http://localhost:8080/main.bundle.js:29506:25)
    at Zone.run (http://localhost:8080/polyfills.bundle.js:16826:25)
    at Zone.run (http://localhost:8080/main.bundle.js:11473:43)
    at zoneBoundFn (http://localhost:8080/polyfills.bundle.js:16803:27)
    at lib$es6$promise$$internal$$tryCatch (http://localhost:8080/polyfills.bundle.js:16051:18)
    at lib$es6$promise$$internal$$invokeCallback (http://localhost:8080/polyfills.bundle.js:16063:19)
    at lib$es6$promise$$internal$$publish (http://localhost:8080/polyfills.bundle.js:16034:13)
    at http://localhost:8080/polyfills.bundle.js:15706:11
    at Zone.run (http://localhost:8080/polyfills.bundle.js:16826:25)
    at zoneBoundFn (http://localhost:8080/polyfills.bundle.js:16803:27)
    at lib$es6$promise$asap$$flush (http://localhost:8080/polyfills.bundle.js:15845:11)
```

**Comment by muaz-khan** [comment]
Are you still getting this error? (using latest RecordRTC.js)

**Comment by BkunS** [comment]
I'm getting the same error with current version: 5.4.6. It should be mediaRecorder.start() instead.

**Comment by muaz-khan** [comment]
Please locate the bug and insert following code quickly before that line:

```javascript
if(mediaRecorder instanceof MediaRecorder) {
    alert('This bug makes sense. Because MediaRecorder API do not have any "record" method.');
}
else {
    alert('It is RecordRTC own implementation. So this should not be a bug. Because all RecordRTC modules has "record" methods.');
}
mediaRecorder.record();
```

**Comment by BkunS** [comment]
@muaz-khan Tried on both browsers: Chrome 66 and Firefox 60:
![screenshot from 2018-05-20 11-00-11](https://user-images.githubusercontent.com/11668298/40280158-5637bcf2-5c1d-11e8-842d-b3805f226a9b.png)
![screenshot from 2018-05-20 11-01-11](https://user-images.githubusercontent.com/11668298/40280159-58fa3a14-5c1d-11e8-8a01-d1839f7f3909.png)

Inserted the code inside function initRecorder() right before mediaRecorder.record().
Error only happens with options: {
        mimeType: 'audio/wav',
        recorderType: StereoAudioRecorder,
        /* numberOfAudioChannels: 1 */
}.
'audio/ogg' or 'audio/webm' with MediaStreamRecorder works.

**Comment by muaz-khan** [comment]
I'm using [StereoAudioRecorder](https://recordrtc.org/StereoAudioRecorder.html) in this demo. Please test and share chrome console logs:

* https://www.webrtc-experiment.com/RecordRTC/simple-demos/edge-audio-recording.html

**Comment by robinmanuelthiel** [comment]
Same error for me. How can I help @muaz-khan?

**Comment by mbalign** [comment]
I installed 5.5.8 today via NPM and get this issue, did anyone ever find a solution?  

The demo I'm basing my code on works fine, so I'm confused: https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/16khz-audio-recording.html
