### ISSUE TITLE
empty blob after recording audio with recordRTC

### ISSUE THREAD

**Issue by jpmarten** [muaz-khan/RecordRTC#335]
I have been using https://cdn.webrtc-experiment.com/RecordRTC.js with great success for almost 2 years now, but since a couple of days my web service does not work properly anymore. I record audio with StereoAudioRecorder (with NumberOfChannels = 1) and after having stopped the recorder I observe that the blob is empty now.  If I go back to the recordRTC version of June 2017, everything works fine again.

What can be the cause of the change in behavior?

Best regards
Jean-Pierre Martens

**Comment by dmitrii-snytkin** [comment]
+1. @jpmarten Can you say working version, which you use?

**Comment by muaz-khan** [comment]
@jpmarten Are you using [`clearRecordedData`](http://recordrtc.org/RecordRTC.html#clearRecordedData) somewhere in your codes? Or [`reset`](http://recordrtc.org/RecordRTC.html#reset) method?

Please try following demo:

* https://www.webrtc-experiment.com/RecordRTC/simple-demos/edge-audio-recording.html

**Comment by jpmarten** [comment]
To Dimitri:
I downloaded the version directly from the address I mentioned above, and this was on Sunday October 1.

To Muaz:
I do not use clearRecordedData nor reset in my code. The only thing I use is stopRecording.

**Comment by jpmarten** [comment]
Dear Muaz

Sorry to insist.
[test_record_webRTC.txt](https://github.com/muaz-khan/RecordRTC/files/1364503/test_record_webRTC.txt)


I tried the edge-audio-recording demo, but it did not work properly on my laptop (there were always loud beep tones audible and the audio continued to play). Starting from your demo I made another demo which is in attach (changed extension from html to txt) and which does work all-right. In this demo works properly on my laptop.

In my web application (script record_webRTC.js), I record  my speech and I press a 'listen' button (where I do stopRecording(stopRecordingCallback);). The callback function is
      function stopRecordingCallback() {
          audio.pause();
          audio.src = URL.createObjectURL(recordRTC.blob); }

Below you finde the messages I received from recordRTC (using Chrome debugger) for two versions: the latest one from the website and the one from June. The differences are small (2 more messages in the old version) but apparently important because in the new version I only get a RIF-header (44 bytes) without samples whereas in the old version I get samples all-right. Can my input help you to pinpoint the problem?

With new version:
Using recorderType: StereoAudioRecorder
RecordRTC.js:2472 StereoAudioRecorder is set to record number of channels:  1
RecordRTC.js:2889 sample-rate 48000
RecordRTC.js:2890 buffer-size 4096
RecordRTC.js:693 Recorder state changed: recording
RecordRTC.js:93 Initialized recorderType: StereoAudioRecorder for output-type: audio
RecordRTC.js:53 started recording audio stream.
RecordRTC.js:693 Recorder state changed: recording
RecordRTC.js:119 Stopped recording audio stream.
RecordRTC.js:693 Recorder state changed: stopped
RecordRTC.js:160 audio/wav -> 44.0 Bytes

With version of June 2017:
RecordRTC.js:968 Using recorderType: StereoAudioRecorder
RecordRTC.js:2288 StereoAudioRecorder is set to record number of channels:  1
RecordRTC.js:2703 sample-rate 48000
RecordRTC.js:2704 buffer-size 4096
RecordRTC.js:665 Recorder state changed: recording
RecordRTC.js:93 Initialized recorderType: StereoAudioRecorder for output-type: audio
RecordRTC.js:53 started recording audio stream.
RecordRTC.js:665 Recorder state changed: recording
RecordRTC.js:119 Stopped recording audio stream.
  stopRecording @ RecordRTC.js:119
  listenBut_pressed @ record_webRTC.js:474
RecordRTC.js:665 Recorder state changed: stopped
RecordRTC.js:161 audio/wav -> 197 KB

**Comment by dmitrii-snytkin** [comment]
@muaz-khan I've checked [your link](https://www.webrtc-experiment.com/RecordRTC/simple-demos/edge-audio-recording.html). It doesn't work. Chrome 61.0.3163.100. Windows 10. I've only microphone on my laptop.

**Comment by dmitrii-snytkin** [comment]
It records. But in audio is only silence.

**Comment by dmitrii-snytkin** [comment]
FF 56.0. It doesn't work too. Behavior is the same.

**Comment by jpmarten** [comment]
Dear Muaz

I wonder whether there is already a solution for the problem I reported. For the time being I keep my application running with the June version of the software, but this means of course that I cannot eprofit from the improvements that were introduced since then in the software.

Best
Jean-Pierre

**Comment by muaz-khan** [comment]
Please make sure that you're use this demo:

* https://www.webrtc-experiment.com/RecordRTC/simple-demos/audio-recording.html

Silence output means either [bufferSize](https://github.com/muaz-khan/RecordRTC#buffersize) or [sampleRate](https://github.com/muaz-khan/RecordRTC#samplerate) are mismatched. (least possibility is that audio track is inactive/stopped)

Above demo is using WebAudio solution; however you can omit/remove `recorderType` parameter to force MediaRecorder API. In this case, please make sure that your stream includes merely audio tracks.

Also make sure that microphone is active. You can set `audio.srcObject` to keep audio-track opened. You need to set this before using RecordRTC or similar recording solutions (recorderjs/MediaRecorder/etc.).

**Comment by jpmarten** [comment]
Dear Muaz

Your demo now works correctly, but it does not allow me to record multiple times. The small demo I made (and
which is in attach) is similar but is made to record multiple times (per time: do start recording, stop recording and
play recording; repeat that). Using the last version of recordRTC (as configured in the html file) I cannot record
a second time, but with my copy inserted -- which is actually the June version of recordRTC-- it works perfectly.
Maybe this example can help you to figure out what can explain the difference in behavior of the two versions.

Best
Jean-Pierre

**Comment by jpmarten** [comment]
Dear Muaz

After more than a year I want to come back to issue 335 which was never really solved. However, I am now able to define the problem a lot better than I did in November 2017.

Just for the record: my intention is to record a number of speech samples one by one and to upload them them one by one to a server. In order to do so I use the StereoAudioRecorder with 1 channel. 

When I started to use recordRTC I could construct a recorder once and I could subsequently issue as many (startRecording, recording, stopRecording) sequences as I wanted. With the current version 5.5.4 (and probably all versions later than 5.4.2) I can only perform one such a sequence. During the other sequences the recorder state is set to 'recording', but nothing is recorded. During these sequences, the function onAudioProcessDataAvailable is only called once (at the time the recorder is stopped). During the first sequence it is called every time a new data buffer was recorded.

I tried to figure out what the cause of the problem was, but I failed because I am insufficiently trained in JS. But maybe my description rings a bell for you.

Thanks for taking the time to read my comment
Jean-Pierre Martens

**Comment by jpmarten** [comment]
Dear Muaz

[I send you an e-mail because I wanted to add a small demo]

I have developed a speech therapy tool and one of its aims is to record speech samples
one by one and to store them as wave files. In order to do so I use the stereoAudioRecorder
from your recordRTC module. This normally works well but it has happened twice in a year
that the recordings were empty (see issue 335 on Github).

I now would like to solve the problem once and for all, and therefore I started from
your demo "simple audio recording ..." and I changed my tool so that it follows the
same logic as in your demo, but with recorderType = stereoAudioRecorder". It seemed to
work fine until I made my 6-th recording. Then I got the following error:

    Uncaught DOMException: Failed to construct 'AudioContext': The number of hardware contexts
    provided (6) is greater than or equal to the maximum bound (6).
    at new StereoAudioRecorder (http://localhost:8080/js/recordRTC-latest.js:2887:43)
    at initRecorder (http://localhost:8080/js/recordRTC-latest.js:93:25)
    at Object.startRecording (http://localhost:8080/js/recordRTC-latest.js:74:9)
    at HTMLButtonElement.recBut.onclick (http://localhost:8080/js/test_record_webRT

I then stripped your demo to about 100 lines (see attachment) and I tried to record
multiple speech samples. Without specifying a recorderType, everything worked fine, but
after adding the StereoAudioRecorder, I got the same error (at recording 6) as mentioned
above.

Is there a problem in the StereoAudioRecorder or is there something I can do to
avoid the error?

Best regards
Jean-Pierre Martens

**Comment by jpmarten** [comment]
Dear Muaz-Kahn

On February 16, I sent you an e-mail concerning a problem I encountered with the
StereoAudioRecorder in your otherwise marvelous recordRTC module. I also added
a very tiny demo in the hope that this could facilitate the identification of the problem
(which may well be due to something I do wrong).

I write you because I did not receive any reply on my previous mail. Even if your answer
would be that you have other engagements now and therefore insufficient time to attend my
problem, I would still like to receive that answer, so that I can start to search for another
solution.

Just in case you do no longer have my previous mail, I repeat it below and I attach the demo again.

I sincerely hope to hear from you soon.

Best
Jean-Pierre Martens
(Ghent University, retired but still active in managing a speech therapy tool called ASISTO
which embeds speech technology tools for patient assessments)

=========================================================================
I have developed a speech therapy tool and one of its aims is to record speech samples
one by one and to store them as wave files. In order to do so I use the stereoAudioRecorder
from your recordRTC module. This normally works well but it has happened twice in a year
that the recordings were empty (see issue 335 on Github).

I now would like to solve the problem once and for all, and therefore I started from
your demo "simple audio recording ..." and I changed my tool so that it follows the
same logic as in your demo, but with recorderType = stereoAudioRecorder". It seemed to
work fine until I made my 6-th recording. Then I got the following error:

    Uncaught DOMException: Failed to construct 'AudioContext': The number of hardware contexts
    provided (6) is greater than or equal to the maximum bound (6).
    at new StereoAudioRecorder (http://localhost:8080/js/recordRTC-latest.js:2887:43)
    at initRecorder (http://localhost:8080/js/recordRTC-latest.js:93:25)
    at Object.startRecording (http://localhost:8080/js/recordRTC-latest.js:74:9)
    at HTMLButtonElement.recBut.onclick (http://localhost:8080/js/test_record_webRT

I then stripped your demo to about 100 lines (see attachment) and I tried to record
multiple speech samples. Without specifying a recorderType, everything worked fine, but
after adding the StereoAudioRecorder, I got the same error (at recording 6) as mentioned
above.

Is there a problem in the StereoAudioRecorder or is there something I can do to
avoid the error?
