### ISSUE TITLE
Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6)

### ISSUE THREAD

**Issue by rusith** [muaz-khan/RecordRTC#385]
We use RecordRTC to record the window in a Chrome extension. The recording works fine except when we try to record the same window more continuously, it throws an error

```
background.js:18632 DOMException: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).
    at getMixedAudioStream (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:91194:47)
    at MultiStreamsMixer.getMixedStream (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:91150:32)
    at MultiStreamRecorder.record (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:91427:55)
    at initRecorder (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:86221:23)
    at Object.startRecording (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:86201:9)
    at RecordingManager._callee3$ (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:85681:32)
    at tryCatch (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:39004:40)
    at Generator.invoke [as _invoke] (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:39238:22)
    at Generator.prototype.(anonymous function) [as next] (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:39056:21)
    at step (chrome-extension://lfgkmcnkcgpggkkdcblgecnbinfoeipb/scripts/background.js:5405:30)
```

Error throws when in

```JS
this.$initializeRecordRtc();
this.state.rtc.startRecording(); // this line
```

$initializeRecordRtc() is something like below

```JS
  $initializeRecordRtc() {
    const config = {
      mimeType: 'video/webm',
      disableLogs: false,
      frameInterval: this.screenInfo.frameInterval,
      canvas: {
        width: this.screenInfo.width,
        height: this.screenInfo.height,
      },
      video: {
        width: this.screenInfo.width,
        height: this.screenInfo.height,
      },
      bufferSize: 16384,
      leftChannel: false,
    };
    if (this.state.rtc) {
      this.$stopAndClearRecorder();
    }
    this.state.rtc = RecordRTC([this.state.tabStream, this.state.audioStream], config);
  }
```

My code which stops the recording is something like this

```JS
$stopAndClearRecorder() {
    try {
      if (this.state.rtc) {
        if (this.state.rtc.getState() === 'recording') {
          this.state.rtc.stopRecording();
        }
        this.state.rtc.clearRecordedData();
      }
    } catch (e) {
      /* ignored */
    }
  }
```

Thanks in advance !

**Comment by jaymo107** [comment]
I think you should destroy the recorder too once you've cleared the data? Maybe `this.state.rtc.destroy()`?

If you're re-creating instances of the recorder each time there is a limit on how many you can create.

**Comment by rusith** [comment]
I updated the issue, now Im calling the destroy function but still the error is there.

**Comment by rusith** [comment]
```
DISTROYING
background.js:86887 undefined
background.js:86888 {AudioContext: ƒ}
background.js:86895 RecordRTC is destroyed.  // Destroy function has called 
```

**Comment by rusith** [comment]
I checked the RecordRTC's `destroy` function. when i call the destroy function. Storage.AudioContextConstructor is `undefined`.

```JS
           /*Code from RecordRTC.js from line 747 (I added the console.logs below)*/
            console.log('DISTROYING');
            console.log(Storage.AudioContextConstructor); // This is undefined
            console.log(Storage); // This is a function
            if (Storage.AudioContextConstructor) {
                Storage.AudioContextConstructor.close();
                Storage.AudioContextConstructor = null;
            }
```

**Comment by osukono** [comment]
You should have only one `AudioContext` in the page.

**Comment by rusith** [comment]
RecordRTC should handle that, right ? the problem is `Storage.AudioContextConstructor` is `undefined` when i call the `destroy` function. so the `AudioContext` created when starting the recording is not closing when the recording ends.

**Comment by thijstriemstra** [comment]
Same issue as https://github.com/muaz-khan/RecordRTC/issues/344

**Comment by lmmProject** [comment]
destroy useless
